In [3]:
import numpy as np
import torch
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
x = torch.Tensor(5, 3)
print(x)


 1.3922e-07  4.5577e-41 -2.4690e-08
 3.0966e-41 -2.6348e+14  4.5576e-41
-2.6317e+14  4.5576e-41 -2.1703e+14
 4.5576e-41 -2.6221e+14  4.5576e-41
-2.6220e+14  4.5576e-41 -2.6478e+14
[torch.FloatTensor of size 5x3]



In [5]:
x = torch.rand(5, 3)
print(x)


 0.9928  0.6871  0.4284
 0.0256  0.4857  0.5842
 0.8076  0.8411  0.1220
 0.7240  0.5910  0.4349
 0.0806  0.1109  0.0520
[torch.FloatTensor of size 5x3]



In [7]:
y = torch.randn(5, 3)
print(y)


-1.9019  0.3193 -2.2202
-0.9354  0.0014 -0.1036
 0.5700  0.4088  1.1897
-1.8623  0.2417  0.6442
 0.3295  0.6171 -1.3206
[torch.FloatTensor of size 5x3]



In [9]:
print(x+y)


-3.4607 -0.1289 -2.3744
-0.1797 -0.5826 -3.5024
 2.1729 -0.5956  1.3190
-0.8548  0.7472  1.2071
-0.4715 -0.2382 -1.2192
[torch.FloatTensor of size 5x3]



In [10]:
print(torch.add(x, y))


-3.4607 -0.1289 -2.3744
-0.1797 -0.5826 -3.5024
 2.1729 -0.5956  1.3190
-0.8548  0.7472  1.2071
-0.4715 -0.2382 -1.2192
[torch.FloatTensor of size 5x3]



In [11]:
temp = y
temp.add_(x)
print(temp)


-3.4607 -0.1289 -2.3744
-0.1797 -0.5826 -3.5024
 2.1729 -0.5956  1.3190
-0.8548  0.7472  1.2071
-0.4715 -0.2382 -1.2192
[torch.FloatTensor of size 5x3]



In [12]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,2)
print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [14]:
b = x.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [15]:
x.add_(1)
print(x)
print(b)


 1.9166  1.9643  1.1065  1.2604
 1.1934  1.0538  1.5969  1.5264
 1.3411  1.1017  1.0633  1.1630
 1.2221  1.0951  1.6611  1.5375
[torch.FloatTensor of size 4x4]

[[1.9165963 1.9642584 1.1065052 1.2603698]
 [1.193409  1.0537574 1.5968912 1.5263636]
 [1.3411009 1.1016777 1.0632757 1.1630158]
 [1.2221112 1.0951486 1.6611094 1.5375383]]


In [16]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [17]:
from torch.autograd import Variable as var

In [18]:
x = var(torch.ones(2,2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [19]:
y = x+3
print(y)

Variable containing:
 4  4
 4  4
[torch.FloatTensor of size 2x2]



In [20]:
print(y.grad_fn)

In [21]:
z = 2*y*y
out = z.mean()
print(z, out)

Variable containing:
 32  32
 32  32
[torch.FloatTensor of size 2x2]
 Variable containing:
 32
[torch.FloatTensor of size 1]



In [22]:
out.backward()

In [23]:
print(x.grad)

Variable containing:
 4  4
 4  4
[torch.FloatTensor of size 2x2]



In [27]:
x = torch.rand(3)
x = var(x, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y*2
    
print(y)

Variable containing:
 1701.4702
   28.1141
  411.7164
[torch.FloatTensor of size 3]



In [28]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
  204.8000
 2048.0000
    0.2048
[torch.FloatTensor of size 3]

